services:
  db:
    container_name: test-container
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tests