spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tests
    username: postgres
    password: admin123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  paths-to-match:
    - /api/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
